### ISSUE TITLE
Write a documentation describing how the supervisor and orchestrator

### ISSUE THREAD

**Issue by isoteemu** [LiquidAI-project/wasmiot-supervisor#27]
Write a documentation describing for supervisor and orchestrator. It should describe; How to deploy them; how they operate internally and how they communicate.

Deadline: 2023-12-31

```[tasklist]
### Documentation
- [x] Deployment / installation documentation
- [ ] Supervisor technical documentation
- [x] Orhestrator technical documentation
- [ ] Overview documentation
```

**Comment by trkks** [comment]
## Orchestrator technical documentation
Per module:
- [ ] Discovery and devices
- [ ] WebAssembly, modules and description
- [ ] Deployment manifest and orchestration
- [ ] Execution

## Supervisor technical documentation
- [ ] Device description
- [ ] Deployment self-setup
- [ ] WebAssembly, execution, control and data-flow

**Comment by trkks** [comment]
I was planning  to do the supervisor OpenAPI document [like the orchestrator has](https://github.com/LiquidAI-project/wasmiot-orchestrator/blob/trkks-docs/docs/orchestrator/api.yml) but it seems like a lot of work for little benefit. The orchestrator document was at least immediately beneficial in creating a CLI client, but as supervisor is not meant to be used in such a way it seems pointless having to write and maintain an API description of it.

So unless it is needed, I would consider "supervisor technical documentation" done.
